cartpole-ppo:
    env: financial-markets-env-short-selling-v0
    run: RiskAutoregressivePPO
    stop:
        timesteps_total: 100000000
    local_dir: ./.logging
    config:
        # Works for both torch and tf.
        framework: torch
        seed: 1010
        #num_sgd_iter: 5
        #vf_loss_coeff: 0.0001
        lr: 5e-05
        env_config:
            include_cash_asset: true
            include_unobservable_market_state_information_for_evaluation: false
            env_config_id: 32
            force_dict_obs_space: true
            conditional_minkowski_encoding: true
            include_risk_penalty_in_state: false
            conditional_minkowski_encoding_type: "S4"
        model:
            fcnet_hiddens: [512, 256, 128]
            vf_share_layers: true
            custom_model: TorchCustomAutoregressiveModelS4
            custom_model_config:
                fcnet_hiddens_autoreg_branches: [64]
                fc_hiddens_uniform_autoreg_branches: [64]
            custom_action_dist: TorchAutoregressiveDirichletDistributionS4
            #use_lstm: True
            #lstm_use_prev_action: True
            #lstm_use_prev_reward: True
            #lstm_cell_size: 256
        batch_mode: complete_episodes
        evaluation_num_workers: 1
        evaluation_interval: 5
        custom_eval_function: custom_eval_function_lambda_penalty
        callbacks: EvaluationLoggerCallback
    verbose: 1