cartpole-ppo:
    env: financial-markets-env-short-selling-v0
    run: Baseline
    stop:
        timesteps_total: 5000000
    local_dir: ./.logging
    checkpoint_config:
        checkpoint_at_end: true
        checkpoint_frequency: 500
    config:
        framework: torch
        seed: 1010
        lr: 1e-06
        env_config:
            include_cash_asset: true
            include_unobservable_market_state_information_for_evaluation: false
            env_config_id: 52
            force_single_simplex: true
            constraints_conditional_minkowski_encoding_type: S4
        model:
            fcnet_hiddens: [512, 256, 128]
            vf_share_layers: true
            custom_model: CustomBaselineModel
            custom_model_config:
                fcnet_hiddens_autoreg_branches: [64]
            custom_action_dist: TorchBaselinePolytopeDistribution
        batch_mode: complete_episodes
        evaluation_num_workers: 1
        evaluation_interval: 20
        custom_eval_function: custom_eval_function_lambda_penalty
        callbacks: EvaluationLoggerCallback
        evaluation_amount_episodes: 4000
        evaluation_allow_backtesting: true
    verbose: 1
